"""Default configuration"""

HELLO_WHAT = "Configurable Default World"

RECIPE_INGREDIENTS_MAX = 20
RECIPE_INSTRUCTIONS_MAX = 20
RECIPE_CATEGORIES_MAX = 20
RECIPE_USER_REVIEWS_MAX = 1000
RECIPE_LIST_PAGE_SIZE = 5
REVIEW_LIST_PAGE_SIZE = 5
